package com.example.tdminsight.ui.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.tdminsight.model.TdmInput
import com.example.tdminsight.model.TdmResult
import com.example.tdminsight.ui.components.ResultCard

@Composable
fun ResultScreen(
    result: TdmResult,
    onBackToReview: () -> Unit,
    onOpenDisclaimer: () -> Unit,
    onStartNewCase: () -> Unit,
    modifier: Modifier = Modifier,
    input: TdmInput? = null
) {
    Column(
        modifier = modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(24.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text(
            text = "Calculation Complete",
            style = MaterialTheme.typography.headlineSmall
        )
        Text(
            text = "Academic prototype output generated by the validated calculation engine. This is not a treatment recommendation.",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        input?.let { caseInput ->
            Surface(
                modifier = Modifier.fillMaxWidth(),
                shape = MaterialTheme.shapes.medium,
                color = MaterialTheme.colorScheme.secondaryContainer
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(4.dp)
                ) {
                    Text(
                        text = caseInput.workflow.displayName,
                        style = MaterialTheme.typography.titleMedium
                    )
                    caseInput.patientParameters["caseId"]
                        ?.takeIf { it.isNotBlank() }
                        ?.let { caseId ->
                            Text(
                                text = "Case ID: $caseId",
                                style = MaterialTheme.typography.bodyMedium
                            )
                        }
                }
            }
        }

        if (result.intermediateValues.isNotEmpty()) {
            ResultCard(
                title = "Intermediate Values",
                values = result.intermediateValues
            )
        }
        if (result.pharmacokineticParameters.isNotEmpty()) {
            ResultCard(
                title = "Pharmacokinetic Parameters",
                values = result.pharmacokineticParameters
            )
        }
        if (result.finalValues.isNotEmpty()) {
            ResultCard(
                title = "Final Values",
                values = result.finalValues
            )
        }

        Text(
            text = "Calculation Details",
            style = MaterialTheme.typography.titleLarge
        )

        result.explanation.forEachIndexed { index, step ->
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.surfaceVariant
                )
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(6.dp)
                ) {
                    Text(
                        text = "${index + 1}. ${step.title}",
                        style = MaterialTheme.typography.titleMedium
                    )
                    Text(
                        text = step.detail,
                        style = MaterialTheme.typography.bodyMedium
                    )
                }
            }
        }

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            OutlinedButton(
                onClick = onBackToReview,
                modifier = Modifier.weight(1f)
            ) {
                Text("Back to Review")
            }
            Button(
                onClick = onStartNewCase,
                modifier = Modifier.weight(1f)
            ) {
                Text("New Case")
            }
        }

        TextButton(
            onClick = onOpenDisclaimer,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("View Academic Disclaimer")
        }
    }
}
